"""GitHub integration — repo creation, commit, and push.

Uses the `gh` CLI for GitHub API operations and git for version control.
Requires `gh auth login` to have been completed.
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class GitHubResult:
    """Result of a GitHub shipping operation."""

    repo_url: str
    commit_sha: str
    files_committed: list[str] = field(default_factory=list)


class GitHubShipError(Exception):
    """Raised when GitHub operations fail."""


def _run(cmd: list[str], *, cwd: str | None = None) -> subprocess.CompletedProcess[str]:
    """Run a subprocess command, raising on failure."""
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=cwd)
    if result.returncode != 0:
        raise GitHubShipError(
            f"Command failed: {' '.join(cmd)}\nstderr: {result.stderr.strip()}"
        )
    return result


def check_gh_auth() -> bool:
    """Verify gh CLI is authenticated."""
    try:
        _run(["gh", "auth", "status"])
        return True
    except (GitHubShipError, FileNotFoundError):
        return False


def repo_exists(repo_name: str) -> bool:
    """Check if a GitHub repo already exists."""
    result = subprocess.run(
        ["gh", "repo", "view", repo_name, "--json", "name"],
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def create_repo(repo_name: str, *, private: bool = True) -> str:
    """Create a new GitHub repo and return its URL.

    Args:
        repo_name: Full name (owner/repo) or just repo name.
        private: Whether to create a private repo.

    Returns:
        The HTTPS clone URL of the created repo.
    """
    visibility = "--private" if private else "--public"
    _run(["gh", "repo", "create", repo_name, visibility])
    # Get the URL of the newly created repo
    return get_repo_url(repo_name)


def get_repo_url(repo_name: str) -> str:
    """Get the clone URL for an existing repo."""
    # If no owner specified, get the authenticated user's login
    if "/" not in repo_name:
        user_result = _run(["gh", "api", "user", "--jq", ".login"])
        owner = user_result.stdout.strip()
        repo_name = f"{owner}/{repo_name}"
    result = _run(["gh", "repo", "view", repo_name, "--json", "url"])
    data = json.loads(result.stdout)
    return str(data["url"])


def write_files(output_dir: Path, files: dict[str, str]) -> list[str]:
    """Write generated files to disk.

    Args:
        output_dir: Directory to write files into.
        files: Mapping of relative path -> file content.

    Returns:
        List of written file paths (relative).
    """
    written: list[str] = []
    for rel_path, content in files.items():
        full_path = output_dir / rel_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content, encoding="utf-8")
        written.append(rel_path)
    return written


def compute_file_fingerprint(content: str) -> str:
    """Compute SHA-256 fingerprint for file content."""
    return hashlib.sha256(content.encode()).hexdigest()[:16]


def init_and_commit(
    output_dir: Path,
    *,
    message: str = "feat: initial code generated by FlowForge",
) -> str:
    """Initialize git repo, add all files, and commit.

    Returns:
        The commit SHA.
    """
    cwd = str(output_dir)
    _run(["git", "init"], cwd=cwd)
    _run(["git", "add", "."], cwd=cwd)
    _run(["git", "commit", "-m", message], cwd=cwd)
    result = _run(["git", "rev-parse", "HEAD"], cwd=cwd)
    return result.stdout.strip()


def push_to_remote(output_dir: Path, *, repo_url: str) -> None:
    """Add remote and push to GitHub."""
    cwd = str(output_dir)
    _run(["git", "remote", "add", "origin", repo_url], cwd=cwd)
    _run(["git", "branch", "-M", "main"], cwd=cwd)
    _run(["git", "push", "-u", "origin", "main"], cwd=cwd)


def ship_to_github(
    output_dir: Path,
    *,
    repo_name: str | None = None,
    create_if_missing: bool = True,
    private: bool = True,
    commit_message: str = "feat: initial code generated by FlowForge",
) -> GitHubResult:
    """Ship generated files to a GitHub repository.

    If repo_name is None, derives from the output directory name.
    Creates a new private repo if it doesn't exist and create_if_missing is True.

    Args:
        output_dir: Directory containing generated files.
        repo_name: GitHub repo name (owner/repo or just repo).
        create_if_missing: Create the repo if it doesn't exist.
        private: Whether to create a private repo.
        commit_message: Git commit message.

    Returns:
        GitHubResult with repo URL, commit SHA, and file list.

    Raises:
        GitHubShipError: If any operation fails.
    """
    if not check_gh_auth():
        raise GitHubShipError(
            "GitHub CLI not authenticated. Run `gh auth login` first."
        )

    if repo_name is None:
        repo_name = output_dir.name

    # Get or create repo
    if repo_exists(repo_name):
        repo_url = get_repo_url(repo_name)
    elif create_if_missing:
        repo_url = create_repo(repo_name, private=private)
    else:
        raise GitHubShipError(
            f"Repository '{repo_name}' does not exist and create_if_missing=False"
        )

    # Collect file list
    files_committed = [
        str(p.relative_to(output_dir))
        for p in output_dir.rglob("*")
        if p.is_file() and ".git" not in p.parts
    ]

    # Init, commit, push
    commit_sha = init_and_commit(output_dir, message=commit_message)
    push_to_remote(output_dir, repo_url=repo_url)

    return GitHubResult(
        repo_url=repo_url,
        commit_sha=commit_sha,
        files_committed=files_committed,
    )
